// Marking + detection of plugin-generated messages.
//
// PROBLEM: everything the plugin pushes into a session travels as a plain
// user-role message (`promptAsync` has no other channel), so a primary
// session's history mixes REAL user prompts with machine-generated text:
// subagent completion / error / timeout / denial-loop notices, buffered
// drain flushes, the handoff kickoff and the DOC_SUMMARY prompt. Consumers
// that scan the history for "what did the USER last ask" (lastUserGoal in
// handoff.js) must tell the two apart — live-verified failure: kickoff #1
// in live-test 3 carried a subagent wake notice as `Letztes Ziel:`.
//
// MECHANISM: every text part the plugin sends carries
// `metadata: { agentIntercom: true }`. Verified empirically on the installed
// opencode 1.17.15 (see scratch notes intercom-wake-notice-fix):
//   - `TextPartInput.metadata` is accepted by `promptAsync` (204) and
//     persisted VERBATIM — `session.messages` returns the part with the
//     metadata object intact.
//   - The part's text still reaches the provider request unchanged
//     (captured with a fake OpenAI endpoint), so notices stay model-visible.
// Metadata is plugin-defined and opaque to opencode. The SDK's `synthetic`
// flag also round-trips, but it is an opencode-INTERPRETED flag whose
// rendering/visibility semantics we did not measure — metadata is the
// side-effect-free choice.
//
// This module is a pure leaf (imports nothing) so BOTH sides can share it:
// client.js — the single send-side chokepoint (postNotice + promptSession
// are the only two functions in src/ that call session.promptAsync) — and
// handoff.js, whose module discipline forbids importing client.js.

// The metadata key every plugin-sent text part carries.
export const INTERCOM_MESSAGE_METADATA_KEY = "agentIntercom"

// Builds the text part used for EVERY message the plugin sends via the
// session API. Single central marking point: client.js uses this for both
// postNotice and promptSession, which covers all four notice paths
// (completion / error / timeout / denial-loop), the drain flush + abortDrain
// re-posts, the handoff kickoff, the DOC_SUMMARY prompt and spawn task
// prompts. A new send path added later inherits the marker for free as long
// as it goes through client.js — which is the repo rule anyway.
export function intercomTextPart(text) {
  return {
    type: "text",
    text,
    metadata: { [INTERCOM_MESSAGE_METADATA_KEY]: true },
  }
}

// True when `message` was generated by this plugin. Accepts both message
// shapes lastUserGoal handles:
//   - opencode session.messages shape: `{ info: { role }, parts: [...] }`
//   - chat-completion shape: `{ role, content: [...] }`
// ANY part carrying the marker makes the whole message plugin-generated —
// the plugin only ever sends single-part messages, so a mixed message
// cannot originate here; the ANY-rule additionally stays correct if opencode
// ever appends bookkeeping parts to the same message.
export function isPluginGeneratedMessage(message) {
  if (!message || typeof message !== "object") return false
  const parts = Array.isArray(message.parts)
    ? message.parts
    : Array.isArray(message.content)
      ? message.content
      : []
  for (const p of parts) {
    if (
      p &&
      typeof p === "object" &&
      p.metadata &&
      typeof p.metadata === "object" &&
      p.metadata[INTERCOM_MESSAGE_METADATA_KEY] === true
    ) {
      return true
    }
  }
  return false
}

// Best-effort BACKSTOP for messages that predate the metadata marker or come
// from a version-skewed companion TUI (the TUI posts its abort notice via its
// own promptAsync; an older published TUI build carries no metadata). These
// are the verbatim leading strings of every plugin-composed message kind:
//   - "🔔 agent-intercom:"  completion / error / timeout notices + TUI abort
//   - "⚠️ agent-intercom:"  denial-loop notice
//   - "## Stand / Aktueller Zustand"  handoff kickoff (SECTION_STAND in
//     project.js — duplicated here as a literal because this module must
//     stay a leaf)
//   - "You are about to be replaced by a fresh orchestrator session"
//     DOC_SUMMARY_PROMPT (only in a session that survived a failed handoff)
// False positives require a human to START a prompt with one of these exact
// strings; the consequence is merely that the scan falls back to an earlier
// user message.
const LEGACY_PLUGIN_MESSAGE_PREFIXES = [
  "🔔 agent-intercom:",
  "⚠️ agent-intercom:",
  "## Stand / Aktueller Zustand",
  "You are about to be replaced by a fresh orchestrator session",
]

export function looksLikePluginMessage(text) {
  if (typeof text !== "string") return false
  const t = text.replace(/^\s+/, "")
  return LEGACY_PLUGIN_MESSAGE_PREFIXES.some((p) => t.startsWith(p))
}
